/**
 * Stock Manager API
 * Stock Manager API reference for developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@oferto.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WarehouseReq } from './warehouseReq';


/**
 * Class representing a product tracked by the application.
 */
export interface ProductReq { 
    /**
     * Product status.
     */
    active: boolean;
    /**
     * Product description.
     */
    description?: string;
    /**
     * Product family.
     */
    family: ProductReq.FamilyEnum;
    /**
     * Unique identifier of the entity. No two entities can have the same id.
     */
    id: number;
    /**
     * Product name.
     */
    name: string;
    /**
     * Product price.
     */
    price: number;
    warehouse: WarehouseReq;
}
export namespace ProductReq {
    export type FamilyEnum = 'ELECTRONICS' | 'FASHION' | 'PERISHABLE';
    export const FamilyEnum = {
        Electronics: 'ELECTRONICS' as FamilyEnum,
        Fashion: 'FASHION' as FamilyEnum,
        Perishable: 'PERISHABLE' as FamilyEnum
    };
}


