/**
 * Stock Manager API
 * Stock Manager API reference for developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@oferto.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Class representing a warehouse tracked by the application.
 */
export interface WarehouseReq { 
    /**
     * Address of the warehouse.
     */
    address?: string;
    /**
     * Unique identifier of the entity. No two entities can have the same id.
     */
    id: number;
    /**
     * Latitude of the warehouse.
     */
    latitude: number;
    /**
     * Longitude of the warehouse.
     */
    longitude: number;
    /**
     * Name of the warehouse.
     */
    name: string;
}

